-- BeProud · Fase 11B — seed SOCIAL v2 (15 tareas).

insert into public.tasks_catalog (
  slug, title, description, category, base_points, icon, photo_hint,
  duration_min, calories_burned, equipment_required, muscle_groups,
  difficulty, contraindications, evidence_level, references_text, subcategory
) values
('call_family','Llamar a la familia','Llamada de al menos 15 min.','social',15,'📞','Captura del log de llamadas.',
 15, 5, '{}', '{none}', 1, '{}', 'strong',
 'Holt-Lunstad et al. (2010), doi:10.1371/journal.pmed.1000316 — social ties & longevity.', 'social_indoor'),
('coffee_friend','Café con un amigo','Quedar a tomar café con alguien.','social',20,'☕','Foto del café o lugar.',
 60, 0, '{}', '{none}', 1, '{}', 'strong',
 'Holt-Lunstad et al. (2010).', 'social_outdoor'),
('attend_event','Asistir a un evento','Concierto, charla, meetup.','social',25,'🎟️','Foto del evento o entrada.',
 90, 60, '{}', '{none}', 2, '{}', 'moderate',
 'Pillemer et al. (2017).', 'social_outdoor'),
('volunteer_session','Voluntariado','Sesión de voluntariado.','social',40,'🤝','Foto en el lugar.',
 120, 80, '{}', '{none}', 2, '{}', 'strong',
 'Yeung et al. (2017), doi:10.1136/bmjopen-2017-014632.', 'social_outdoor'),
('compliment_someone','Halagar a alguien','Cumplido sincero a alguien.','social',5,'💬','Captura del chat o nota.',
 5, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Lyubomirsky et al. (2005).', 'social_indoor'),
('dinner_friends','Cena con amigos','Compartir cena con amigos.','social',30,'🍽️','Foto de la mesa.',
 120, 0, '{}', '{none}', 1, '{}', 'strong',
 'Holt-Lunstad et al. (2010).', 'social_indoor'),
('group_activity','Actividad en grupo','Deporte, juego o actividad en grupo.','social',30,'🎲','Foto del grupo.',
 90, 200, '{}', '{cardio_system}', 2, '{}', 'moderate',
 'Eime et al. (2013), doi:10.1186/1479-5868-10-98.', 'social_outdoor'),
('reach_out_friend','Mensaje a un amigo lejano','Escribir a alguien con quien no hablas.','social',15,'💌','Captura del mensaje.',
 10, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Liu et al. (2022).', 'social_indoor'),
('club_meetup','Asistir a club','Reunión de club o asociación.','social',30,'🏛️','Foto en el local.',
 120, 60, '{}', '{none}', 2, '{}', 'moderate',
 'Putnam (2000).', 'social_indoor'),
('teach_skill','Enseñar a alguien','Enseñar una habilidad personal.','social',25,'🧑‍🏫','Captura del momento.',
 60, 30, '{}', '{none}', 2, '{}', 'moderate',
 'Fiorella & Mayer (2013).', 'social_indoor'),
('walk_with_friend','Pasear con alguien','Paseo de 30+ min con compañía.','social',20,'🚶‍♂️','Foto del paseo.',
 30, 130, '{}', '{cardio_system}', 1, '{}', 'strong',
 'Bratman et al. (2015).', 'social_outdoor'),
('handwritten_letter','Carta escrita a mano','Carta a alguien especial.','social',25,'✉️','Foto de la carta.',
 30, 10, '{}', '{none}', 2, '{}', 'consensus',
 'Pennebaker (1997).', 'social_indoor'),
('host_dinner','Hacer una cena en casa','Recibir invitados en casa.','social',40,'🏠','Foto de la mesa servida.',
 180, 120, '{}', '{none}', 3, '{}', 'moderate',
 'Holt-Lunstad et al. (2010).', 'social_indoor'),
('attend_workshop','Asistir a taller','Workshop o taller práctico.','social',30,'🛠️','Foto del taller.',
 120, 80, '{}', '{none}', 2, '{}', 'consensus',
 'Putnam (2000).', 'social_outdoor'),
('weekly_quality_time','Tiempo de calidad','2h sin móvil con pareja/hijos/familia.','social',30,'❤️','Foto del momento.',
 120, 30, '{}', '{none}', 1, '{}', 'strong',
 'Holt-Lunstad et al. (2010).', 'social_indoor')
on conflict (slug) do update set
  title              = excluded.title,
  description        = excluded.description,
  category           = excluded.category,
  base_points        = excluded.base_points,
  icon               = excluded.icon,
  photo_hint         = excluded.photo_hint,
  duration_min       = excluded.duration_min,
  calories_burned    = excluded.calories_burned,
  equipment_required = excluded.equipment_required,
  muscle_groups      = excluded.muscle_groups,
  difficulty         = excluded.difficulty,
  contraindications  = excluded.contraindications,
  evidence_level     = excluded.evidence_level,
  references_text    = excluded.references_text,
  subcategory        = excluded.subcategory;
