-- BeProud · Fase 11B — seed WELLBEING v2 (25 tareas).

insert into public.tasks_catalog (
  slug, title, description, category, base_points, icon, photo_hint,
  duration_min, calories_burned, equipment_required, muscle_groups,
  difficulty, contraindications, evidence_level, references_text, subcategory
) values
('meditate_10min','Meditar 10 min','Meditación guiada o silenciosa.','wellbeing',15,'🧘','App de meditación o foto del lugar.',
 10, 10, '{}', '{none}', 1, '{}', 'strong',
 'Goyal et al. (2014), doi:10.1001/jamainternmed.2013.13018 — meditation & wellbeing.', 'meditation'),
('meditate_20min','Meditar 20 min','Sesión más larga de meditación.','wellbeing',25,'🧘‍♂️','Captura de la app.',
 20, 15, '{}', '{none}', 2, '{}', 'strong',
 'Goyal et al. (2014).', 'meditation'),
('meditate_30min','Meditar 30 min','Sesión profunda de meditación.','wellbeing',35,'🧘‍♀️','App o lugar de meditación.',
 30, 20, '{}', '{none}', 3, '{}', 'strong',
 'Tang et al. (2015), doi:10.1038/nrn3916.', 'meditation'),
('journal_entry','Entrada de diario','Escribir entrada del día.','wellbeing',15,'📓','Foto de la página escrita.',
 15, 10, '{}', '{none}', 1, '{}', 'strong',
 'Pennebaker (1997), doi:10.1111/j.1467-9280.1997.tb00403.x.', 'none'),
('gratitude_list','Lista de gratitud','Apuntar 3 cosas por las que estoy agradecido.','wellbeing',10,'🙏','Lista escrita.',
 5, 5, '{}', '{none}', 1, '{}', 'strong',
 'Emmons & McCullough (2003), doi:10.1037/0022-3514.84.2.377.', 'none'),
('deep_sleep','Dormir 8 horas','Sueño reparador de al menos 8h.','wellbeing',20,'😴','App de sueño.',
 480, 0, '{}', '{none}', 1, '{}', 'strong',
 'Hartmann (2018), doi:10.1093/sleep/zsx193 — sleep duration & mortality.', 'sleep'),
('sleep_consistent','Dormir a la misma hora','Acostarse y levantarse a la misma hora.','wellbeing',15,'⏰','App de sueño con horarios.',
 null, 0, '{}', '{none}', 1, '{}', 'strong',
 'Buysse (2014), doi:10.5665/sleep.3286 — sleep regularity.', 'sleep'),
('no_screens_before_bed','Sin pantallas antes de dormir','60 min sin pantallas antes de dormir.','wellbeing',15,'📵','Foto de la mesilla sin móvil.',
 60, 0, '{}', '{none}', 2, '{}', 'strong',
 'Chang et al. (2015), doi:10.1073/pnas.1418490112 — light exposure & sleep.', 'sleep'),
('no_social_media','Día sin redes sociales','24h sin abrir redes.','wellbeing',30,'📵','Captura del tiempo en pantalla.',
 null, 0, '{}', '{none}', 3, '{}', 'moderate',
 'Hunt et al. (2018), doi:10.1521/jscp.2018.37.10.751 — limiting social media.', 'none'),
('digital_detox_hour','1h sin pantallas','60 minutos sin móvil ni pantallas.','wellbeing',10,'🌿','Foto de actividad sin pantallas.',
 60, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Hunt et al. (2018).', 'none'),
('breathing_exercise','Ejercicio de respiración','Sesión de respiración consciente (4-7-8 o similar).','wellbeing',10,'🌬️','App de respiración o foto.',
 5, 5, '{}', '{none}', 1, '{}', 'strong',
 'Zaccaro et al. (2018), doi:10.3389/fnhum.2018.00353.', 'meditation'),
('cold_shower','Ducha fría','Ducha fría de al menos 2 min.','wellbeing',15,'🚿','Foto post-ducha o ducha encendida.',
 5, 10, '{}', '{none}', 3, '{cardiac}', 'weak',
 'Buijze et al. (2016), doi:10.1371/journal.pone.0161749 — cold shower & sick leave.', 'none'),
('nature_walk','Paseo por la naturaleza','Paseo en entorno natural.','wellbeing',20,'🌳','Foto del paisaje.',
 30, 100, '{}', '{cardio_system,legs}', 1, '{}', 'strong',
 'Bratman et al. (2015), doi:10.1073/pnas.1510459112 — nature & rumination.', 'none'),
('forest_bathing','Shinrin-yoku 60 min','Baño de bosque consciente.','wellbeing',35,'🌲','Foto del bosque.',
 60, 180, '{}', '{cardio_system}', 1, '{}', 'moderate',
 'Li et al. (2010), doi:10.1007/s12199-009-0091-z.', 'none'),
('mindful_walk_15min','Paseo consciente 15 min','Paseo prestando atención plena.','wellbeing',12,'🚶','Foto del entorno.',
 15, 50, '{}', '{cardio_system}', 1, '{}', 'moderate',
 'Bratman et al. (2015).', 'meditation'),
('body_scan','Body scan 15 min','Escaneo corporal de relajación.','wellbeing',15,'🧠','Foto en mat.',
 15, 10, '{mat}', '{none}', 1, '{}', 'moderate',
 'Kabat-Zinn (1990).', 'meditation'),
('warm_bath','Baño caliente','Baño caliente de 20 min.','wellbeing',12,'🛁','Foto de la bañera.',
 20, 0, '{}', '{none}', 1, '{cardiac,pregnancy}', 'weak',
 'Liao et al. (2002).', 'none'),
('therapy_session','Sesión de terapia','Sesión con psicólogo/a.','wellbeing',40,'🛋️','Captura de la app de terapia o agenda.',
 60, 0, '{}', '{none}', 2, '{}', 'strong',
 'Cuijpers et al. (2014).', 'none'),
('hobbies_30min','Hobby personal 30 min','Actividad creativa o lúdica.','wellbeing',15,'🎨','Foto de la actividad.',
 30, 30, '{}', '{none}', 1, '{}', 'moderate',
 'Pressman et al. (2009), doi:10.1097/PSY.0b013e3181a51bf3.', 'none'),
('music_listening','Escuchar música 30 min','Escuchar música activamente.','wellbeing',8,'🎶','Pantalla del reproductor.',
 30, 0, '{}', '{none}', 1, '{}', 'weak',
 'Pelletier (2004).', 'none'),
('petting_pet','Pasar tiempo con mascota','Tiempo de calidad con tu mascota.','wellbeing',10,'🐶','Foto con la mascota.',
 30, 30, '{}', '{none}', 1, '{}', 'moderate',
 'McConnell et al. (2011).', 'none'),
('sunlight_15min','15 min de sol','Exposición a luz solar.','wellbeing',10,'☀️','Foto al aire libre.',
 15, 30, '{}', '{none}', 1, '{}', 'strong',
 'Holick (2007), doi:10.1056/NEJMra070553.', 'none'),
('nap_20min','Siesta 20 min','Siesta corta reparadora.','wellbeing',10,'🛏️','Foto de la cama o reloj con alarma.',
 20, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Mednick et al. (2003), doi:10.1038/nn1078.', 'sleep'),
('massage_self','Auto-masaje 15 min','Foam rolling o masaje manual.','wellbeing',12,'💆','Foam roller o pelota.',
 15, 25, '{mat}', '{flexibility,full_body}', 1, '{}', 'weak',
 'Wiewelhove et al. (2019).', 'none'),
('digital_sundown','Apagar todo a las 22:00','Pantallas off desde las 22:00.','wellbeing',15,'🌙','Foto de pantalla apagada.',
 null, 0, '{}', '{none}', 2, '{}', 'moderate',
 'Chang et al. (2015).', 'sleep')
on conflict (slug) do update set
  title              = excluded.title,
  description        = excluded.description,
  category           = excluded.category,
  base_points        = excluded.base_points,
  icon               = excluded.icon,
  photo_hint         = excluded.photo_hint,
  duration_min       = excluded.duration_min,
  calories_burned    = excluded.calories_burned,
  equipment_required = excluded.equipment_required,
  muscle_groups      = excluded.muscle_groups,
  difficulty         = excluded.difficulty,
  contraindications  = excluded.contraindications,
  evidence_level     = excluded.evidence_level,
  references_text    = excluded.references_text,
  subcategory        = excluded.subcategory;
