-- BeProud · Fase 11B — seed STUDY v2 (30 tareas).

insert into public.tasks_catalog (
  slug, title, description, category, base_points, icon, photo_hint,
  duration_min, calories_burned, equipment_required, muscle_groups,
  difficulty, contraindications, evidence_level, references_text, subcategory
) values
('read_30min','Leer 30 minutos','Lectura concentrada de 30 minutos.','study',20,'📖','Foto del libro abierto o e-reader.',
 30, 25, '{}', '{none}', 1, '{}', 'strong',
 'Bavishi et al. (2016), doi:10.1016/j.socscimed.2016.07.014 — lectura y longevidad.', 'reading'),
('read_book_chapter','Leer un capítulo','Terminar un capítulo entero.','study',15,'📚','Foto del libro/capítulo terminado.',
 25, 20, '{}', '{none}', 1, '{}', 'moderate',
 'Bavishi et al. (2016).', 'reading'),
('language_duolingo','Sesión Duolingo','Completar la sesión diaria.','study',10,'🦉','Captura de la app con la sesión completada.',
 15, 10, '{}', '{none}', 1, '{}', 'moderate',
 'Vesselinov & Grego (2012).', 'language'),
('language_practice_30min','Practicar idioma 30 min','Estudio enfocado de idiomas.','study',20,'🗣️','Cuaderno o app de idiomas.',
 30, 20, '{}', '{none}', 2, '{}', 'strong',
 'Lightbown & Spada (2013) — How Languages are Learned.', 'language'),
('online_course_lesson','Lección de curso online','Una lección entera (Coursera, Udemy…).','study',20,'💻','Captura de la lección o avance.',
 45, 30, '{}', '{none}', 2, '{}', 'moderate',
 'Means et al. (2013) — meta-análisis online learning.', 'course'),
('study_session_1h','Sesión de estudio 1 hora','1 hora estudiando con foco.','study',30,'📝','Escritorio con apuntes y temporizador.',
 60, 40, '{}', '{none}', 2, '{}', 'strong',
 'Sweller (2011) — Cognitive load theory.', 'deep_focus'),
('take_notes','Tomar apuntes','Apuntes estructurados de un tema.','study',15,'✍️','Foto de los apuntes.',
 30, 20, '{}', '{none}', 1, '{}', 'strong',
 'Mueller & Oppenheimer (2014), doi:10.1177/0956797614524581 — pen vs laptop notes.', 'reading'),
('practice_problems','Hacer ejercicios','Resolver ejercicios o problemas.','study',20,'🧩','Ejercicios resueltos.',
 30, 25, '{}', '{none}', 2, '{}', 'strong',
 'Karpicke & Roediger (2008) — testing effect.', 'deep_focus'),
('flashcards_review','Repasar flashcards','Sesión Anki/Quizlet.','study',10,'🃏','Captura de la app.',
 15, 10, '{}', '{none}', 1, '{}', 'strong',
 'Karpicke & Bauernschmidt (2011), doi:10.1037/a0023956 — spaced retrieval.', 'reading'),
('write_summary','Escribir resumen','Resumen de un tema/capítulo.','study',20,'📄','Resumen escrito o documento.',
 30, 20, '{}', '{none}', 2, '{}', 'strong',
 'Hattie & Donoghue (2016).', 'reading'),
('watch_educational_video','Ver vídeo educativo','Vídeo o documental educativo.','study',10,'🎬','Captura del vídeo.',
 30, 15, '{}', '{none}', 1, '{}', 'weak',
 'Mayer (2009) — multimedia learning.', 'course'),
('podcast_education','Podcast educativo','Episodio educativo completo.','study',10,'🎧','Captura de la app de podcast.',
 30, 15, '{}', '{none}', 1, '{}', 'weak',
 'Consenso, 2024.', 'course'),
('coding_kata','Kata de programación','Resolver un kata o reto.','study',30,'💻','Editor con código resuelto.',
 45, 30, '{}', '{none}', 3, '{}', 'moderate',
 'Bjork (1994) — desirable difficulties.', 'deep_focus'),
('memorize_vocab','Memorizar vocabulario','Memorizar 20+ palabras.','study',10,'🧠','Lista de vocabulario.',
 20, 15, '{}', '{none}', 2, '{}', 'strong',
 'Karpicke & Bauernschmidt (2011).', 'language'),
('research_topic','Investigar un tema','Investigación sobre un tema.','study',25,'🔎','Notas o pestañas con fuentes.',
 60, 40, '{}', '{none}', 3, '{}', 'moderate',
 'Hofer (2004).', 'deep_focus'),
('read_paper','Leer un paper','Leer un paper académico.','study',30,'📑','PDF abierto con anotaciones.',
 60, 40, '{}', '{none}', 4, '{}', 'strong',
 'Pain (2016) — leer ciencia.', 'reading'),
('summarize_paper','Resumir un paper','Resumen de un paper en 1 página.','study',30,'📝','Resumen escrito.',
 45, 30, '{}', '{none}', 4, '{}', 'strong',
 'Hattie & Donoghue (2016).', 'reading'),
('language_class','Clase de idioma','Clase con profesor (presencial u online).','study',35,'🎓','Captura de la clase o cuaderno.',
 60, 40, '{}', '{none}', 3, '{}', 'strong',
 'Lightbown & Spada (2013).', 'language'),
('immersion_listening','Escucha inmersiva','30 min de podcast/serie en idioma extranjero.','study',15,'🎙️','App o pantalla con el contenido.',
 30, 20, '{}', '{none}', 2, '{}', 'moderate',
 'Krashen (1985) — input hypothesis.', 'language'),
('language_writing','Escribir en idioma','Texto de 200+ palabras.','study',20,'✒️','Foto del texto escrito.',
 30, 20, '{}', '{none}', 3, '{}', 'moderate',
 'Lightbown & Spada (2013).', 'language'),
('exam_practice','Examen de práctica','Hacer un examen de prueba.','study',40,'🧪','Foto del examen.',
 90, 60, '{}', '{none}', 4, '{}', 'strong',
 'Karpicke & Roediger (2008).', 'deep_focus'),
('mind_map','Mapa mental','Crear un mapa mental de un tema.','study',20,'🗺️','Foto del mapa mental.',
 30, 20, '{}', '{none}', 2, '{}', 'moderate',
 'Buzan (1991).', 'reading'),
('teach_someone','Enseñar a alguien','Explicar lo aprendido a alguien.','study',25,'👥','Captura del chat o foto.',
 30, 20, '{}', '{none}', 3, '{}', 'strong',
 'Fiorella & Mayer (2013) — learning by teaching.', 'deep_focus'),
('reading_log','Diario de lectura','Apuntar lo aprendido hoy.','study',15,'📔','Foto de la entrada.',
 15, 10, '{}', '{none}', 1, '{}', 'moderate',
 'Bjork (1994).', 'reading'),
('review_yesterday','Revisar lo de ayer','Repasar lo estudiado el día anterior.','study',15,'🔄','Apuntes con notas de revisión.',
 20, 15, '{}', '{none}', 1, '{}', 'strong',
 'Cepeda et al. (2006), doi:10.1037/0033-2909.132.3.354 — distributed practice.', 'reading'),
('library_session','Sesión en biblioteca','Estudio de 2h en biblioteca/cafetería.','study',45,'📚','Foto del entorno de estudio.',
 120, 80, '{}', '{none}', 3, '{}', 'moderate',
 'Mehta et al. (2012), doi:10.1086/665048 — ambient sound and creativity.', 'deep_focus'),
('write_essay','Escribir un ensayo','Ensayo de 500+ palabras.','study',45,'📃','Documento o foto del texto.',
 90, 60, '{}', '{none}', 4, '{}', 'moderate',
 'Hayes & Flower (1980).', 'deep_focus'),
('lecture_attendance','Asistir a charla','Conferencia o seminario.','study',25,'🎤','Foto del evento.',
 90, 60, '{}', '{none}', 1, '{}', 'consensus',
 'Consenso, 2024.', 'course'),
('book_finished','Terminar un libro','Acabar un libro completo.','study',60,'📘','Foto de la última página.',
 null, null, '{}', '{none}', 3, '{}', 'strong',
 'Bavishi et al. (2016).', 'reading'),
('typing_practice','Mecanografía 15 min','Mejorar velocidad de tecleo.','study',10,'⌨️','Captura de la app de tipos.',
 15, 10, '{}', '{none}', 1, '{wrist}', 'weak',
 'Consenso, 2024.', 'course')
on conflict (slug) do update set
  title              = excluded.title,
  description        = excluded.description,
  category           = excluded.category,
  base_points        = excluded.base_points,
  icon               = excluded.icon,
  photo_hint         = excluded.photo_hint,
  duration_min       = excluded.duration_min,
  calories_burned    = excluded.calories_burned,
  equipment_required = excluded.equipment_required,
  muscle_groups      = excluded.muscle_groups,
  difficulty         = excluded.difficulty,
  contraindications  = excluded.contraindications,
  evidence_level     = excluded.evidence_level,
  references_text    = excluded.references_text,
  subcategory        = excluded.subcategory;
