-- BeProud · Fase 11B — seed FITNESS v2 (cardio, fuerza, mobility, flexibility).
-- UPSERT por slug: enriquece existentes y añade nuevas. Las tareas legacy
-- (gym_session, hike_outdoor, etc.) también reciben metadata aquí.

insert into public.tasks_catalog (
  slug, title, description, category, base_points, icon, photo_hint,
  duration_min, calories_burned, equipment_required, muscle_groups,
  difficulty, contraindications, evidence_level, references_text, subcategory
) values
-- ─── CARDIO LISS (12) ─────────────────────────────────────────────────────
('walk_30min','Caminar 30 minutos','Paseo enérgico de 30 minutos.','fitness',15,'🚶','App de pasos con duración o foto al aire libre.',
 30, 130, '{}', '{cardio_system,legs}', 1, '{}', 'strong',
 'Pedersen & Saltin (2015), doi:10.1111/sms.12581 — exercise as medicine.', 'cardio_liss'),
('walk_10k_steps','10.000 pasos','Completar 10.000 pasos en el día.','fitness',20,'👟','Captura app de pasos mostrando ≥10.000.',
 80, 350, '{}', '{cardio_system,legs}', 2, '{}', 'moderate',
 'Bassett et al. (2017), doi:10.1097/MSS.0000000000001179 — pasos diarios y mortalidad.', 'cardio_liss'),
('run_30min','Correr 30 minutos','Carrera continua a ritmo moderado.','fitness',40,'🏃','App de running con tiempo y distancia, o foto al aire libre.',
 30, 280, '{}', '{cardio_system,legs}', 3, '{knee,ankle,cardiac}', 'strong',
 'Lee et al. (2014), doi:10.1016/j.jacc.2014.04.058 — running y mortalidad.', 'cardio_liss'),
('run_intervals','Correr intervalos','5x3 min rápido + 1 min trote.','fitness',50,'🏃','App con perfil de intervalos visible.',
 25, 280, '{}', '{cardio_system,legs}', 4, '{knee,ankle,cardiac}', 'strong',
 'Helgerud et al. (2007), doi:10.1249/mss.0b013e3180304570.', 'cardio_hiit'),
('run_long','Correr 60+ min','Tirada larga aeróbica (Z2).','fitness',70,'🏃','Mapa de la ruta o app con duración.',
 60, 560, '{}', '{cardio_system,legs}', 4, '{knee,ankle,cardiac}', 'strong',
 'Maffetone & Laursen (2020) — entrenamiento de baja intensidad.', 'cardio_liss'),
('cycling_1h','Bicicleta 1 hora','Salida en bici de al menos una hora.','fitness',40,'🚴','Bici, casco o vista del trayecto al aire libre.',
 60, 420, '{bicycle}', '{cardio_system,legs}', 2, '{cardiac}', 'strong',
 'Oja et al. (2011), doi:10.1111/j.1600-0838.2010.01299.x — cycling y salud.', 'cardio_liss'),
('cycling_indoor','Bici estática 30 min','Spinning o bici indoor.','fitness',30,'🚲','App de la bici o foto del rodillo.',
 30, 250, '{bicycle}', '{cardio_system,legs}', 2, '{cardiac}', 'moderate',
 'Consenso clínico, 2024.', 'cardio_liss'),
('swim_30min','Nadar 30 minutos','Nadar 30 minutos continuos.','fitness',40,'🏊','Foto en piscina/playa o gorro y gafas.',
 30, 240, '{}', '{full_body,cardio_system,shoulders,back}', 3, '{shoulder,cardiac}', 'strong',
 'Tanaka (2009), doi:10.2165/00007256-200939050-00004.', 'cardio_liss'),
('hike_outdoor','Senderismo','Ruta de senderismo al aire libre.','fitness',45,'🥾','Foto del paisaje, sendero o GPS de la ruta.',
 90, 540, '{}', '{cardio_system,legs,glutes}', 2, '{knee,ankle}', 'strong',
 'Mitten et al. (2018), doi:10.1177/1559827616658229 — naturaleza y salud.', 'cardio_liss'),
('rowing_machine','Remo 20 min','Remo en máquina a ritmo estable.','fitness',35,'🚣','Pantalla de la máquina con tiempo y distancia.',
 20, 220, '{gym_full}', '{back,arms,legs,cardio_system,full_body}', 3, '{lower_back,cardiac}', 'moderate',
 'Hagerman (1984), doi:10.2165/00007256-198401040-00006.', 'cardio_liss'),
('elliptical_30min','Elíptica 30 min','Sesión continua en elíptica.','fitness',30,'🌀','Pantalla de la máquina al terminar.',
 30, 240, '{gym_full}', '{cardio_system,legs}', 2, '{cardiac}', 'moderate',
 'Consenso clínico, 2024.', 'cardio_liss'),
('jump_rope_15min','Saltar a la cuerda 15 min','Sesiones de cuerda de 1-2 min con descanso.','fitness',30,'🪢','Cuerda en mano o app contadora.',
 15, 180, '{mat}', '{cardio_system,legs,full_body}', 3, '{knee,ankle,cardiac}', 'moderate',
 'Trecroci et al. (2015), doi:10.1080/02640414.2015.1064151.', 'cardio_hiit'),
-- ─── CARDIO HIIT (8) ──────────────────────────────────────────────────────
('hiit_20min','HIIT 20 min','Sesión de alta intensidad por intervalos.','fitness',35,'⚡','Foto post-entrenamiento o app de HIIT.',
 20, 240, '{}', '{full_body,cardio_system}', 4, '{cardiac,knee,lower_back}', 'strong',
 'Gibala et al. (2012), doi:10.1113/jphysiol.2011.224725.', 'cardio_hiit'),
('tabata_4min','Tabata 4 min','8x(20s on / 10s off) máximo esfuerzo.','fitness',20,'⏱️','App de Tabata o vídeo de la ronda.',
 4, 60, '{}', '{full_body,cardio_system}', 5, '{cardiac,knee}', 'strong',
 'Tabata et al. (1996), PMID:8897392.', 'cardio_hiit'),
('burpees_50','50 burpees','50 burpees repartidos en series.','fitness',25,'💢','Vídeo o foto haciendo burpees.',
 10, 100, '{}', '{full_body,cardio_system}', 4, '{wrist,knee,lower_back,cardiac}', 'moderate',
 'Consenso clínico, 2024.', 'cardio_hiit'),
('mountain_climbers_3min','Mountain climbers 3 min','3 minutos a ritmo alto.','fitness',15,'⛰️','Vídeo o foto durante el ejercicio.',
 5, 50, '{mat}', '{core,cardio_system,shoulders}', 3, '{wrist,shoulder,cardiac}', 'moderate',
 'Consenso clínico, 2024.', 'cardio_hiit'),
('sprints_track','Sprints 6x30s','Sprints máximos con descanso 90s.','fitness',45,'🏁','Foto en pista o app con intervalos.',
 25, 220, '{}', '{legs,cardio_system}', 5, '{knee,ankle,cardiac}', 'strong',
 'Burgomaster et al. (2008), doi:10.1113/jphysiol.2007.142109.', 'cardio_hiit'),
('battle_ropes_10min','Battle ropes 10 min','Intervalos con cuerdas.','fitness',30,'〰️','Foto en el rack de cuerdas.',
 10, 130, '{gym_full}', '{shoulders,arms,core,cardio_system}', 4, '{shoulder,cardiac}', 'weak',
 'Calatayud et al. (2015) — entrenamiento con cuerdas.', 'cardio_hiit'),
('kettlebell_swings_5x20','KB swings 5x20','5 series de 20 swings rusos.','fitness',30,'🛎️','Foto con la kettlebell.',
 12, 150, '{kettlebell}', '{glutes,back,core,cardio_system}', 4, '{lower_back}', 'moderate',
 'McGill & Marshall (2012), doi:10.1519/JSC.0b013e31822c40dc.', 'cardio_hiit'),
('circuit_bodyweight','Circuito peso corporal','5 estaciones x 3 rondas.','fitness',30,'🔁','Diagrama del circuito o foto post.',
 25, 200, '{mat}', '{full_body,cardio_system}', 3, '{knee,wrist,cardiac}', 'moderate',
 'Consenso clínico, 2024.', 'cardio_hiit'),
-- ─── STRENGTH COMPOUND (20) ───────────────────────────────────────────────
('squat_bodyweight_50','50 sentadillas peso corporal','50 sentadillas profundas.','fitness',15,'🦵','Foto haciendo sentadillas.',
 8, 60, '{}', '{legs,glutes,core}', 1, '{knee}', 'strong',
 'Schoenfeld (2010), doi:10.1519/JSC.0b013e3181e840f3.', 'strength_compound'),
('squats_100','100 sentadillas','100 sentadillas en el día.','fitness',20,'🦵','Foto haciendo sentadillas.',
 12, 120, '{}', '{legs,glutes,core}', 2, '{knee}', 'strong',
 'Schoenfeld (2010), doi:10.1519/JSC.0b013e3181e840f3.', 'strength_compound'),
('back_squat_5x5','Back squat 5x5','Sentadilla con barra 5x5.','fitness',60,'🏋️','Barra cargada en jaula con discos visibles.',
 35, 240, '{gym_full}', '{legs,glutes,core,lower_back}', 4, '{knee,lower_back}', 'strong',
 'ACSM (2009), doi:10.1249/MSS.0b013e3181915670.', 'strength_compound'),
('front_squat_5x5','Front squat 5x5','Sentadilla frontal 5x5.','fitness',60,'🏋️','Barra en posición frontal en gym.',
 30, 220, '{gym_full}', '{legs,glutes,core,shoulders}', 5, '{knee,wrist,lower_back}', 'moderate',
 'Gullett et al. (2009), doi:10.1519/JSC.0b013e3181872adf.', 'strength_compound'),
('deadlift_5x5','Peso muerto 5x5','5 series de 5 reps de peso muerto.','fitness',70,'🏋️','Barra cargada en el suelo.',
 35, 280, '{gym_full}', '{back,legs,glutes,core,lower_back}', 5, '{lower_back,knee}', 'strong',
 'Schoenfeld (2014), doi:10.1519/SSC.0000000000000064.', 'strength_compound'),
('romanian_deadlift','Peso muerto rumano','RDL 4x8.','fitness',55,'🏋️','Barra/mancuernas en posición RDL.',
 25, 200, '{dumbbells,gym_full}', '{back,glutes,legs,lower_back}', 4, '{lower_back}', 'strong',
 'Schoenfeld (2014).', 'strength_compound'),
('bench_press_5x5','Press banca 5x5','Press banca 5x5.','fitness',60,'🏋️','Banca con barra cargada y seguros.',
 30, 200, '{gym_full}', '{chest,shoulders,arms}', 4, '{shoulder,wrist}', 'strong',
 'Saeterbakken et al. (2017), doi:10.1519/JSC.0000000000001603.', 'strength_compound'),
('overhead_press_5x5','Press militar 5x5','Press de pie con barra.','fitness',55,'🏋️','Barra a la altura de hombros.',
 25, 180, '{gym_full}', '{shoulders,arms,core}', 4, '{shoulder,neck,lower_back}', 'strong',
 'Saeterbakken et al. (2013).', 'strength_compound'),
('pullups_10','10 dominadas','10 dominadas estrictas.','fitness',20,'💪','Foto en la barra o vídeo capturado.',
 8, 60, '{pullup_bar}', '{back,arms,shoulders}', 4, '{shoulder,wrist}', 'strong',
 'Youdas et al. (2010), doi:10.1519/JSC.0b013e3181d854dd.', 'strength_compound'),
('pullups_50','50 dominadas','50 dominadas en el día.','fitness',45,'💪','Foto en la barra.',
 25, 200, '{pullup_bar}', '{back,arms,shoulders}', 5, '{shoulder,wrist}', 'strong',
 'Youdas et al. (2010).', 'strength_compound'),
('chinups_10','10 chin-ups','10 dominadas supinas estrictas.','fitness',20,'💪','Barra en posición supina.',
 8, 60, '{pullup_bar}', '{back,arms}', 4, '{shoulder,wrist}', 'strong',
 'Youdas et al. (2010).', 'strength_compound'),
('barbell_row_5x5','Remo con barra 5x5','Remo Pendlay/Yates 5x5.','fitness',55,'🏋️','Barra cargada en posición de remo.',
 25, 200, '{gym_full}', '{back,arms,shoulders,lower_back}', 4, '{lower_back,wrist}', 'strong',
 'Andersen et al. (2014), doi:10.1519/JSC.0000000000000379.', 'strength_compound'),
('dumbbell_row_4x10','Remo mancuerna 4x10','Remo a una mano sobre banco.','fitness',35,'🏋️','Mancuerna y banco visible.',
 20, 130, '{dumbbells}', '{back,arms,shoulders}', 3, '{lower_back}', 'strong',
 'Consenso clínico, 2024.', 'strength_compound'),
('dumbbell_press_4x10','Press mancuerna 4x10','Press de pecho con mancuernas.','fitness',45,'🏋️','Banca con mancuernas.',
 25, 180, '{dumbbells}', '{chest,shoulders,arms}', 3, '{shoulder,wrist}', 'strong',
 'Saeterbakken et al. (2017).', 'strength_compound'),
('dumbbell_shoulder_press','Press hombro mancuerna','Press de pie 4x8.','fitness',40,'🏋️','Mancuernas a altura de hombros.',
 20, 140, '{dumbbells}', '{shoulders,arms,core}', 3, '{shoulder,neck}', 'strong',
 'Consenso clínico, 2024.', 'strength_compound'),
('lunges_walking','Zancadas caminando','3x20m de lunges.','fitness',30,'🚶','Foto en pasillo o pista.',
 12, 110, '{}', '{legs,glutes,core}', 2, '{knee}', 'moderate',
 'Riemann et al. (2012), doi:10.1519/JSC.0b013e3182362b6e.', 'strength_compound'),
('bulgarian_split_squat','Búlgaras 4x10','Bulgarian split squat con mancuernas.','fitness',45,'🦵','Pie elevado en banco con mancuernas.',
 18, 160, '{dumbbells}', '{legs,glutes,core}', 4, '{knee,lower_back}', 'moderate',
 'Mackey et al. (2014).', 'strength_compound'),
('dips_3x10','Fondos 3x10','Fondos en paralelas.','fitness',30,'💪','Paralelas o sillas firmes.',
 12, 90, '{pullup_bar,gym_full}', '{chest,arms,shoulders}', 4, '{shoulder,wrist}', 'strong',
 'Bergquist et al. (2018).', 'strength_compound'),
('pushups_50','50 flexiones','50 flexiones repartidas.','fitness',15,'💪','Foto haciendo flexiones.',
 8, 70, '{}', '{chest,arms,shoulders,core}', 2, '{wrist,shoulder}', 'strong',
 'Yang et al. (2019), doi:10.1001/jamanetworkopen.2018.8341.', 'strength_compound'),
('pushups_100','100 flexiones','100 flexiones en el día.','fitness',30,'💪','Foto haciendo flexiones.',
 18, 140, '{}', '{chest,arms,shoulders,core}', 3, '{wrist,shoulder}', 'strong',
 'Yang et al. (2019).', 'strength_compound'),
-- ─── STRENGTH ISOLATION (15) ──────────────────────────────────────────────
('biceps_curl_4x12','Curl bíceps 4x12','Curl con mancuernas a 12 reps.','fitness',25,'💪','Mancuernas en mano.',
 12, 70, '{dumbbells}', '{arms}', 2, '{wrist}', 'moderate',
 'Schoenfeld et al. (2017), doi:10.1519/JSC.0000000000001895.', 'strength_isolation'),
('triceps_extension_4x12','Extensión tríceps 4x12','Extensión vertical con mancuerna.','fitness',25,'💪','Mancuerna sobre cabeza.',
 12, 70, '{dumbbells}', '{arms}', 2, '{shoulder,wrist}', 'moderate',
 'Schoenfeld et al. (2017).', 'strength_isolation'),
('lateral_raises','Elevaciones laterales 3x15','Elevaciones laterales con mancuernas.','fitness',20,'🏋️','Mancuernas a los lados.',
 10, 60, '{dumbbells}', '{shoulders}', 2, '{shoulder}', 'moderate',
 'Consenso clínico, 2024.', 'strength_isolation'),
('chest_fly_4x12','Aperturas pecho 4x12','Aperturas con mancuernas en banco.','fitness',30,'🏋️','Mancuernas en posición de apertura.',
 15, 80, '{dumbbells}', '{chest}', 3, '{shoulder}', 'moderate',
 'Welsch et al. (2005).', 'strength_isolation'),
('leg_extension_4x12','Extensión de cuádriceps 4x12','Extensión en máquina.','fitness',30,'🏋️','Máquina con peso visible.',
 12, 70, '{gym_full}', '{legs}', 2, '{knee}', 'moderate',
 'Consenso clínico, 2024.', 'strength_isolation'),
('leg_curl_4x12','Curl femoral 4x12','Curl en máquina.','fitness',30,'🏋️','Máquina con peso visible.',
 12, 70, '{gym_full}', '{legs}', 2, '{knee,lower_back}', 'moderate',
 'Consenso clínico, 2024.', 'strength_isolation'),
('leg_press_4x10','Prensa de piernas 4x10','Press en máquina.','fitness',45,'🏋️','Prensa con peso inserto.',
 18, 150, '{gym_full}', '{legs,glutes}', 3, '{knee,lower_back}', 'strong',
 'Escamilla et al. (2001), doi:10.1097/00005768-200109000-00018.', 'strength_isolation'),
('calf_raises_4x20','Gemelos 4x20','Elevación de gemelos.','fitness',15,'🦵','En step o máquina.',
 8, 40, '{}', '{legs}', 1, '{ankle}', 'moderate',
 'Consenso clínico, 2024.', 'strength_isolation'),
('hip_thrust_4x10','Hip thrust 4x10','Hip thrust con barra.','fitness',45,'🏋️','Hombros en banco con barra en cadera.',
 20, 140, '{gym_full}', '{glutes,legs,core}', 3, '{lower_back}', 'strong',
 'Contreras et al. (2017), doi:10.1519/JSC.0000000000001405.', 'strength_isolation'),
('glute_bridge_3x15','Puente de glúteos 3x15','Puente de glúteos peso corporal.','fitness',15,'🦵','Espalda apoyada en suelo.',
 8, 40, '{mat}', '{glutes,core}', 1, '{}', 'strong',
 'Boren et al. (2011), doi:10.1519/JSC.0b013e31822c4cf2.', 'strength_isolation'),
('plank_3min','Plancha 3 min','Acumular 3 min de plancha.','fitness',20,'🔥','Foto en plancha.',
 5, 30, '{mat}', '{core,shoulders}', 2, '{wrist,shoulder,lower_back}', 'strong',
 'McGill (2010), doi:10.1519/SSC.0b013e3181df4521.', 'strength_isolation'),
('side_plank_2x60s','Plancha lateral 2x60s','Plancha lateral por lado.','fitness',20,'🔥','Foto en lateral.',
 5, 30, '{mat}', '{core}', 3, '{shoulder,wrist}', 'strong',
 'McGill (2010).', 'strength_isolation'),
('hanging_leg_raises','Elevación de piernas 3x10','Colgado en barra.','fitness',30,'🔥','Barra de dominadas.',
 8, 60, '{pullup_bar}', '{core,arms}', 4, '{shoulder,lower_back}', 'moderate',
 'Consenso clínico, 2024.', 'strength_isolation'),
('ab_wheel_3x10','Ab wheel 3x10','Rueda abdominal.','fitness',30,'⚙️','Rueda en mat.',
 8, 60, '{mat}', '{core,shoulders}', 4, '{lower_back,shoulder}', 'moderate',
 'Escamilla et al. (2010), doi:10.2519/jospt.2010.3243.', 'strength_isolation'),
('face_pulls_3x15','Face pulls 3x15','Face pulls con polea o banda.','fitness',25,'🪢','Banda o polea visible.',
 10, 50, '{resistance_bands,gym_full}', '{shoulders,back}', 2, '{shoulder}', 'moderate',
 'Andersen et al. (2014).', 'strength_isolation'),
-- ─── MOBILITY (8) ─────────────────────────────────────────────────────────
('mobility_hips','Movilidad cadera 10 min','CARs y openers de cadera.','fitness',15,'🤸','Mat y postura de movilidad.',
 10, 40, '{mat}', '{mobility,glutes,legs}', 2, '{}', 'moderate',
 'Behm et al. (2016), doi:10.1139/apnm-2015-0235.', 'mobility'),
('mobility_shoulders','Movilidad hombros 10 min','CARs y rotaciones.','fitness',15,'🤸','Mat o de pie.',
 10, 40, '{mat}', '{mobility,shoulders}', 2, '{}', 'moderate',
 'Behm et al. (2016).', 'mobility'),
('mobility_thoracic','Movilidad torácica 10 min','Aperturas y rotaciones T-spine.','fitness',15,'🤸','En suelo o foam roller.',
 10, 40, '{mat}', '{mobility,back}', 2, '{}', 'moderate',
 'Behm et al. (2016).', 'mobility'),
('mobility_ankles','Movilidad tobillos 10 min','Dorsiflexión + rotaciones.','fitness',12,'🦶','Sentado o de rodillas.',
 10, 35, '{mat}', '{mobility,legs}', 1, '{}', 'moderate',
 'Lima et al. (2018).', 'mobility'),
('foam_rolling_full','Foam rolling 15 min','Recorrido full body.','fitness',20,'🪵','Foam roller en mat.',
 15, 50, '{mat}', '{mobility,full_body}', 1, '{}', 'moderate',
 'Wiewelhove et al. (2019), doi:10.3389/fphys.2019.00376.', 'mobility'),
('cat_cow_5min','Cat-cow 5 min','Movilidad columna.','fitness',8,'🐈','En mat de cuatro patas.',
 5, 20, '{mat}', '{mobility,back,core}', 1, '{}', 'consensus',
 'Consenso clínico, 2024.', 'mobility'),
('hip_flexor_stretch','Estiramiento flexores 10 min','Couch stretch + lunge.','fitness',12,'🧎','Postura de estocada.',
 10, 30, '{mat}', '{mobility,legs,glutes}', 1, '{knee}', 'moderate',
 'Consenso clínico, 2024.', 'mobility'),
('mobility_full_15min','Movilidad full body 15 min','Rutina completa de movilidad.','fitness',25,'🤸','Mat con rutina visible.',
 15, 60, '{mat}', '{mobility,full_body}', 2, '{}', 'moderate',
 'Behm et al. (2016).', 'mobility'),
-- ─── FLEXIBILITY (7) ──────────────────────────────────────────────────────
('stretching_15min','Estiramientos 15 min','Rutina de estiramientos estáticos.','fitness',10,'🤸','Foto haciendo estiramientos.',
 15, 50, '{mat}', '{flexibility,full_body}', 1, '{}', 'moderate',
 'Behm & Chaouachi (2011), doi:10.1007/s00421-011-1879-2.', 'flexibility'),
('yoga_session','Sesión de yoga','Sesión completa de yoga (~30 min).','fitness',25,'🧘','Foto en mat de yoga.',
 30, 120, '{mat}', '{flexibility,full_body,core}', 2, '{wrist,shoulder}', 'strong',
 'Cramer et al. (2013), doi:10.1097/AJP.0b013e31826f0d18.', 'flexibility'),
('yoga_60min','Yoga 60 min','Clase completa de Hatha/Vinyasa.','fitness',45,'🧘','Mat con instructor o app.',
 60, 240, '{mat}', '{flexibility,full_body,core}', 3, '{wrist,shoulder}', 'strong',
 'Cramer et al. (2013).', 'flexibility'),
('pilates_session','Pilates 45 min','Sesión completa de pilates.','fitness',35,'🩰','Mat o reformer.',
 45, 180, '{mat}', '{flexibility,core,full_body}', 3, '{lower_back}', 'moderate',
 'Cruz-Ferreira et al. (2011), doi:10.1097/PHM.0b013e3181e8a90b.', 'flexibility'),
('static_stretch_30min','Estiramientos profundos 30 min','Sesión profunda de estiramientos.','fitness',20,'🧎','Mat y temporizador.',
 30, 90, '{mat}', '{flexibility,full_body}', 2, '{}', 'moderate',
 'Behm & Chaouachi (2011).', 'flexibility'),
('splits_practice','Práctica de splits','15 min de aperturas progresivas.','fitness',20,'🤸','En mat con foto del split.',
 15, 60, '{mat}', '{flexibility,legs,glutes}', 4, '{knee,lower_back}', 'weak',
 'Consenso clínico, 2024.', 'flexibility'),
('neck_stretches_5min','Estiramientos cervicales 5 min','Para tensión de cuello.','fitness',8,'💆','En silla o de pie.',
 5, 15, '{}', '{flexibility,mobility}', 1, '{neck}', 'consensus',
 'Consenso clínico para oficina, 2024.', 'flexibility'),
-- ─── LEGACY (gym_session, sports, dance, climbing, martial arts, core, leg, upper, hike_long) ─
('gym_session','Sesión de gym','Entrenamiento completo en el gimnasio.','fitness',60,'🏋️','Foto en gym: máquinas, pesas o barra cargada.',
 60, 350, '{gym_full}', '{full_body}', 3, '{lower_back,shoulder,knee}', 'strong',
 'ACSM (2009), doi:10.1249/MSS.0b013e3181915670.', 'strength_compound'),
('sports_match','Partido deportivo','Jugar un partido (fútbol, pádel, baloncesto…).','fitness',40,'⚽','Foto del partido o pista.',
 60, 480, '{}', '{full_body,cardio_system}', 3, '{knee,ankle}', 'strong',
 'Bangsbo et al. (2010), doi:10.1111/j.1600-0838.2010.01165.x.', 'cardio_liss'),
('dance_class','Clase de baile','Clase o sesión de baile.','fitness',30,'💃','Foto en sala con instructor.',
 45, 270, '{}', '{full_body,cardio_system}', 2, '{ankle,knee}', 'moderate',
 'Hwang & Braun (2015), doi:10.7453/gahmj.2015.022.', 'cardio_liss'),
('climbing_session','Escalada','Sesión de escalada o boulder.','fitness',50,'🧗','Foto en rocódromo o roca.',
 60, 480, '{}', '{full_body,arms,back,core}', 4, '{shoulder,wrist,ankle}', 'moderate',
 'Watts (2004), doi:10.1080/02640410310001655458.', 'strength_compound'),
('martial_arts_class','Clase de artes marciales','Boxeo, judo, karate, BJJ…','fitness',40,'🥋','Dojo o equipo (kimono, guantes).',
 60, 480, '{}', '{full_body,cardio_system}', 4, '{neck,shoulder,wrist,ankle,knee}', 'moderate',
 'Bu et al. (2010).', 'cardio_hiit'),
('core_workout','Entrenamiento de core','Rutina enfocada al núcleo (15 min).','fitness',20,'🔥','Plancha, dead bug, ab wheel.',
 15, 80, '{mat}', '{core}', 2, '{lower_back}', 'strong',
 'McGill (2010), doi:10.1519/SSC.0b013e3181df4521.', 'strength_isolation'),
('leg_day','Día de pierna','Entrenamiento completo de tren inferior.','fitness',50,'🦵','Jaula con barra o prensa.',
 60, 360, '{gym_full}', '{legs,glutes,core,lower_back}', 4, '{knee,lower_back}', 'strong',
 'Schoenfeld (2010).', 'strength_compound'),
('upper_body_workout','Entrenamiento de torso','Pecho, espalda, hombros y brazos.','fitness',50,'💪','Banca, dominadas o press.',
 60, 320, '{dumbbells,gym_full}', '{chest,back,shoulders,arms}', 3, '{shoulder,wrist}', 'strong',
 'Schoenfeld (2010).', 'strength_compound'),
('hike_outdoor_long','Senderismo largo (4h+)','Ruta de montaña de 4 horas.','fitness',80,'🥾','Vista aérea o GPS de la ruta.',
 240, 1200, '{}', '{cardio_system,legs,glutes}', 4, '{knee,ankle,cardiac}', 'strong',
 'Mitten et al. (2018).', 'cardio_liss')
on conflict (slug) do update set
  title              = excluded.title,
  description        = excluded.description,
  category           = excluded.category,
  base_points        = excluded.base_points,
  icon               = excluded.icon,
  photo_hint         = excluded.photo_hint,
  duration_min       = excluded.duration_min,
  calories_burned    = excluded.calories_burned,
  equipment_required = excluded.equipment_required,
  muscle_groups      = excluded.muscle_groups,
  difficulty         = excluded.difficulty,
  contraindications  = excluded.contraindications,
  evidence_level     = excluded.evidence_level,
  references_text    = excluded.references_text,
  subcategory        = excluded.subcategory;
