-- BeProud · Fase 11B — seed PRODUCTIVITY v2 (30 tareas).

insert into public.tasks_catalog (
  slug, title, description, category, base_points, icon, photo_hint,
  duration_min, calories_burned, equipment_required, muscle_groups,
  difficulty, contraindications, evidence_level, references_text, subcategory
) values
('deep_work_1h','Deep work 1h','1 hora de trabajo profundo sin interrupciones.','productivity',30,'🎯','Escritorio o temporizador completo.',
 60, 40, '{}', '{none}', 3, '{}', 'strong',
 'Newport (2016) — Deep Work.', 'deep_focus'),
('deep_work_2h','Deep work 2h','2 horas de trabajo profundo.','productivity',50,'🎯','Sesiones de pomodoro.',
 120, 80, '{}', '{none}', 4, '{}', 'strong',
 'Newport (2016).', 'deep_focus'),
('deep_work_4h','Deep work 4h','4 bloques de foco al día.','productivity',90,'🎯','Pomodoros encadenados.',
 240, 160, '{}', '{none}', 5, '{}', 'moderate',
 'Newport (2016).', 'deep_focus'),
('inbox_zero','Inbox zero','Bandeja de entrada a 0.','productivity',15,'📭','Email vacío.',
 30, 20, '{}', '{none}', 2, '{}', 'consensus',
 'Mann (2007) — Inbox Zero.', 'none'),
('complete_task_list','Lista de tareas completada','Terminar la lista del día.','productivity',25,'✅','Lista marcada al 100%.',
 null, null, '{}', '{none}', 2, '{}', 'moderate',
 'Locke & Latham (2002), doi:10.1037/0003-066X.57.9.705.', 'none'),
('pomodoro_4','4 pomodoros','Completar 4 pomodoros (≥100 min foco).','productivity',30,'🍅','App de pomodoro.',
 120, 80, '{}', '{none}', 3, '{}', 'moderate',
 'Cirillo (2018).', 'deep_focus'),
('pomodoro_8','8 pomodoros','Completar 8 pomodoros.','productivity',55,'🍅','App con 8 pomodoros.',
 240, 160, '{}', '{none}', 4, '{}', 'moderate',
 'Cirillo (2018).', 'deep_focus'),
('plan_tomorrow','Planificar mañana','Plan del día siguiente escrito.','productivity',10,'📅','Plan/agenda.',
 15, 10, '{}', '{none}', 1, '{}', 'strong',
 'Wieth & Burns (2014) — planning effects.', 'none'),
('weekly_review','Review semanal','Revisión completa de la semana.','productivity',30,'🗓️','Cuaderno o app con review.',
 45, 30, '{}', '{none}', 2, '{}', 'moderate',
 'Allen (2015) — GTD.', 'none'),
('clean_desk','Ordenar escritorio','Dejar el escritorio limpio.','productivity',10,'🧹','Foto del escritorio ordenado.',
 15, 20, '{}', '{none}', 1, '{}', 'weak',
 'Vohs et al. (2013), doi:10.1177/0956797613480186.', 'none'),
('organize_files','Organizar archivos','Organizar archivos digitales.','productivity',20,'📁','Captura de carpetas organizadas.',
 30, 15, '{}', '{none}', 2, '{}', 'consensus',
 'Allen (2015).', 'none'),
('time_blocking','Time blocking','Dividir el día en bloques.','productivity',15,'🧱','Calendario con bloques.',
 15, 10, '{}', '{none}', 2, '{}', 'moderate',
 'Newport (2016).', 'deep_focus'),
('eisenhower_matrix','Matriz Eisenhower','Clasificar tareas urgente/importante.','productivity',15,'🟦','Foto de la matriz.',
 15, 10, '{}', '{none}', 2, '{}', 'consensus',
 'Covey (1989).', 'none'),
('automate_task','Automatizar tarea','Automatizar algo que hagas a menudo.','productivity',30,'🤖','Captura del flujo o script.',
 45, 25, '{}', '{none}', 3, '{}', 'consensus',
 'Allen (2015).', 'deep_focus'),
('one_thing_today','Una sola cosa hoy','Foco en la tarea más importante.','productivity',20,'1️⃣','Captura de la tarea cumplida.',
 null, null, '{}', '{none}', 2, '{}', 'moderate',
 'Keller & Papasan (2013).', 'deep_focus'),
('phone_off_work','Móvil en otro cuarto','Trabajar 1h con el móvil fuera.','productivity',15,'📵','Móvil en otra habitación.',
 60, 40, '{}', '{none}', 2, '{}', 'strong',
 'Ward et al. (2017), doi:10.1086/691462 — brain drain phone.', 'deep_focus'),
('no_meetings_block','Bloque sin reuniones','3h+ sin reuniones.','productivity',20,'🗓️','Calendario con bloque libre.',
 180, 100, '{}', '{none}', 2, '{}', 'moderate',
 'Newport (2016).', 'deep_focus'),
('write_long_form','Escribir long-form 1h','1h escribiendo (post, doc, paper).','productivity',35,'✍️','Editor con texto.',
 60, 40, '{}', '{none}', 4, '{}', 'moderate',
 'Newport (2016).', 'deep_focus'),
('respond_emails_batch','Email batch 30 min','30 min en bloque para email.','productivity',15,'📧','Email cleanup.',
 30, 20, '{}', '{none}', 1, '{}', 'consensus',
 'Allen (2015).', 'none'),
('budget_review','Repaso financiero','Repasar gastos/ingresos del mes.','productivity',25,'💰','App o hoja de cálculo.',
 30, 20, '{}', '{none}', 2, '{}', 'consensus',
 'Consenso, 2024.', 'none'),
('declutter_room','Ordenar una zona','Ordenar/limpiar una zona de casa.','productivity',20,'🧺','Antes/después.',
 30, 80, '{}', '{none}', 1, '{}', 'weak',
 'Saxbe & Repetti (2010).', 'none'),
('home_admin','Tareas administrativas','Trámites, papeleo, llamadas.','productivity',20,'📋','Carpeta o app con trámites.',
 30, 15, '{}', '{none}', 2, '{}', 'consensus',
 'Consenso, 2024.', 'none'),
('learn_keyboard_shortcut','Aprender 3 atajos','Aprender 3 nuevos atajos de teclado.','productivity',10,'⌨️','Lista de atajos.',
 15, 8, '{}', '{none}', 1, '{wrist}', 'consensus',
 'Consenso, 2024.', 'none'),
('hot_journaling','Hot journaling 10 min','Escritura libre sobre el día.','productivity',12,'🔥','Cuaderno con la entrada.',
 10, 5, '{}', '{none}', 1, '{}', 'moderate',
 'Pennebaker (1997).', 'none'),
('weekly_top3','Top 3 semanal','Definir 3 prioridades de la semana.','productivity',15,'⭐','Lista escrita.',
 10, 5, '{}', '{none}', 1, '{}', 'moderate',
 'Allen (2015).', 'none'),
('sunday_prep','Preparar la semana','Domingo: preparar ropa, comida, agenda.','productivity',25,'🗒️','Foto del setup.',
 60, 40, '{}', '{none}', 2, '{}', 'moderate',
 'Allen (2015).', 'none'),
('morning_routine_30','Morning routine 30 min','Rutina mañanera fija.','productivity',15,'🌅','Foto del setup.',
 30, 30, '{}', '{none}', 2, '{}', 'moderate',
 'Duhigg (2012) — Power of Habit.', 'none'),
('habit_tracker_update','Tracker actualizado','Actualizar tu habit tracker.','productivity',8,'📊','Tracker visible.',
 5, 5, '{}', '{none}', 1, '{}', 'moderate',
 'Clear (2018) — Atomic Habits.', 'none'),
('learn_one_tool','Aprender una herramienta','Aprender feature de una herramienta de trabajo.','productivity',20,'🛠️','Captura del tutorial/uso.',
 30, 15, '{}', '{none}', 2, '{}', 'consensus',
 'Consenso, 2024.', 'deep_focus'),
('inbox_unsubscribe','Limpiar suscripciones','Cancelar 10+ suscripciones de email.','productivity',15,'🗑️','Captura de unsubscribe.',
 20, 10, '{}', '{none}', 1, '{}', 'consensus',
 'Mann (2007).', 'none')
on conflict (slug) do update set
  title              = excluded.title,
  description        = excluded.description,
  category           = excluded.category,
  base_points        = excluded.base_points,
  icon               = excluded.icon,
  photo_hint         = excluded.photo_hint,
  duration_min       = excluded.duration_min,
  calories_burned    = excluded.calories_burned,
  equipment_required = excluded.equipment_required,
  muscle_groups      = excluded.muscle_groups,
  difficulty         = excluded.difficulty,
  contraindications  = excluded.contraindications,
  evidence_level     = excluded.evidence_level,
  references_text    = excluded.references_text,
  subcategory        = excluded.subcategory;
