-- BeProud · Fase 11B — seed NUTRITION v2 (30 tareas).

insert into public.tasks_catalog (
  slug, title, description, category, base_points, icon, photo_hint,
  duration_min, calories_burned, equipment_required, muscle_groups,
  difficulty, contraindications, evidence_level, references_text, subcategory
) values
('healthy_breakfast','Desayuno saludable','Desayuno equilibrado y casero.','nutrition',10,'🥑','Foto del desayuno preparado.',
 15, 0, '{}', '{none}', 1, '{}', 'strong',
 'Adolphus et al. (2013), doi:10.3389/fnhum.2013.00425 — desayuno y rendimiento.', 'cooking'),
('healthy_lunch','Comida saludable','Comida equilibrada (proteína, vegetales, carbo complejo).','nutrition',15,'🥗','Foto del plato.',
 30, 0, '{}', '{none}', 1, '{}', 'strong',
 'Mozaffarian (2016), doi:10.1161/CIRCULATIONAHA.115.018585.', 'cooking'),
('healthy_dinner','Cena saludable','Cena ligera y equilibrada.','nutrition',15,'🍲','Foto del plato.',
 30, 0, '{}', '{none}', 1, '{}', 'strong',
 'St-Onge et al. (2017), doi:10.1161/CIR.0000000000000476.', 'cooking'),
('drink_2l_water','Beber 2L de agua','Hidratación adecuada del día.','nutrition',15,'💧','Foto de botellas vacías o app.',
 5, 0, '{}', '{none}', 1, '{}', 'strong',
 'Popkin et al. (2010), doi:10.1111/j.1753-4887.2010.00304.x.', 'hydration'),
('meal_prep','Meal prep','Preparar comidas para 3-5 días.','nutrition',30,'🥘','Foto de tuppers preparados.',
 90, 0, '{}', '{none}', 2, '{}', 'moderate',
 'Wolfson & Bleich (2015), doi:10.1017/S1368980014001943.', 'cooking'),
('home_cooking','Cocinar en casa','Cocinar una comida completa.','nutrition',20,'🍳','Foto de la cocina o el plato.',
 45, 0, '{}', '{none}', 1, '{}', 'strong',
 'Mills et al. (2017), doi:10.3390/nu9050480.', 'cooking'),
('no_junk_food','Día sin comida basura','Sin azúcar refinada, fritos ni ultraprocesados.','nutrition',20,'🚫','Foto del menú del día.',
 null, 0, '{}', '{none}', 2, '{}', 'strong',
 'Monteiro et al. (2018), doi:10.1017/S1368980018003762.', 'none'),
('fruit_serving','Comer fruta','Al menos una pieza de fruta.','nutrition',5,'🍎','Foto de la fruta consumida.',
 5, 0, '{}', '{none}', 1, '{}', 'strong',
 'Aune et al. (2017), doi:10.1093/ije/dyw319 — frutas y mortalidad.', 'none'),
('vegetables_serving','Comer verduras','Ración de verduras en alguna comida.','nutrition',10,'🥦','Foto del plato con verdura.',
 5, 0, '{}', '{none}', 1, '{}', 'strong',
 'Aune et al. (2017).', 'none'),
('track_calories','Registrar comidas','Registrar todo lo comido en una app.','nutrition',10,'📊','Captura de la app de tracking.',
 10, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Burke et al. (2011), doi:10.1016/j.jada.2010.10.008.', 'none'),
('drink_3l_water','Beber 3L de agua','Hidratación intensiva (deportistas).','nutrition',20,'💦','Botellas de agua del día.',
 5, 0, '{}', '{none}', 1, '{cardiac}', 'moderate',
 'Sawka et al. (2007), doi:10.1249/mss.0b013e31802ca597.', 'hydration'),
('protein_target','Cumplir proteína diaria','Llegar a tu objetivo de g de proteína.','nutrition',20,'🥩','Plato con proteína o cálculo en app.',
 null, 0, '{}', '{none}', 2, '{}', 'strong',
 'Morton et al. (2018), doi:10.1136/bjsports-2017-097608.', 'none'),
('fiber_30g','30g de fibra','Llegar a 30g de fibra al día.','nutrition',15,'🌾','Plato con verdura/legumbre/avena.',
 null, 0, '{}', '{none}', 2, '{}', 'strong',
 'Reynolds et al. (2019), doi:10.1016/S0140-6736(18)31809-9.', 'none'),
('home_cook_dinner','Cena casera','Cenar algo cocinado por ti.','nutrition',15,'🍳','Plato de la cena.',
 30, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Mills et al. (2017).', 'cooking'),
('cook_new_recipe','Nueva receta','Probar una receta nueva.','nutrition',20,'📜','Foto de la receta y el plato.',
 60, 0, '{}', '{none}', 2, '{}', 'consensus',
 'Consenso, 2024.', 'cooking'),
('batch_cook_protein','Batch protein','Cocinar 5 raciones de proteína.','nutrition',25,'🍗','Tuppers con proteína.',
 60, 0, '{}', '{none}', 2, '{}', 'moderate',
 'Wolfson & Bleich (2015).', 'cooking'),
('plant_based_meal','Comida 100% vegetal','Una comida basada en plantas.','nutrition',15,'🌱','Plato sin productos animales.',
 30, 0, '{}', '{none}', 1, '{}', 'strong',
 'Satija et al. (2017), doi:10.1016/j.jacc.2017.05.047.', 'cooking'),
('omega3_serving','Pescado azul','Sardina, salmón, caballa.','nutrition',12,'🐟','Plato con pescado azul.',
 null, 0, '{}', '{none}', 1, '{}', 'strong',
 'Mozaffarian & Wu (2011), doi:10.1016/j.jacc.2011.06.063.', 'none'),
('cut_sugar_drinks','Cero azúcar líquida','Día sin refrescos ni zumos azucarados.','nutrition',15,'🥤','Foto de tu bebida (agua/té/café).',
 null, 0, '{}', '{none}', 1, '{}', 'strong',
 'Malik et al. (2019), doi:10.1056/NEJMoa1810013.', 'none'),
('whole_grains','Cereales integrales','Sustituir refinados por integrales.','nutrition',10,'🌾','Plato con avena, arroz integral o quinoa.',
 null, 0, '{}', '{none}', 1, '{}', 'strong',
 'Aune et al. (2016), doi:10.1136/bmj.i2716.', 'none'),
('hydration_morning','Vaso al despertar','500ml de agua al levantarte.','nutrition',5,'🫗','Vaso lleno por la mañana.',
 2, 0, '{}', '{none}', 1, '{}', 'consensus',
 'Consenso clínico, 2024.', 'hydration'),
('herbal_tea','Té sin azúcar','Té o infusión sin azúcar.','nutrition',5,'🍵','Taza de té.',
 5, 0, '{}', '{none}', 1, '{}', 'consensus',
 'Hayat et al. (2015) — té y salud.', 'hydration'),
('caffeine_cap','Café <300mg','No pasarte de cafeína (1-2 cafés).','nutrition',8,'☕','Tazas que llevas.',
 null, 0, '{}', '{none}', 1, '{cardiac}', 'moderate',
 'Wikoff et al. (2017).', 'none'),
('breakfast_protein','Desayuno con proteína','Mín. 25g de proteína al desayuno.','nutrition',15,'🥚','Plato del desayuno.',
 15, 0, '{}', '{none}', 1, '{}', 'strong',
 'Leidy et al. (2015), doi:10.3945/an.114.007146.', 'cooking'),
('mindful_eating','Comer sin pantallas','Una comida sin móvil ni TV.','nutrition',10,'🧘','Mesa preparada sin pantallas.',
 30, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Robinson et al. (2013), doi:10.3945/ajcn.112.045245.', 'none'),
('grocery_healthy','Compra sana','Hacer la compra siguiendo lista saludable.','nutrition',15,'🛒','Carro de la compra.',
 45, 0, '{}', '{none}', 2, '{}', 'consensus',
 'Wansink (2016).', 'none'),
('intermittent_fast_16','Ayuno 16/8','16h de ayuno y ventana de 8h.','nutrition',20,'⏳','App de ayuno con ventana visible.',
 null, 0, '{}', '{none}', 3, '{cardiac,pregnancy}', 'moderate',
 'Patterson & Sears (2017), doi:10.1146/annurev-nutr-071816-064634.', 'none'),
('vegetable_smoothie','Smoothie verde','Smoothie con verduras.','nutrition',10,'🥬','Vaso del smoothie.',
 10, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Boeing et al. (2012).', 'cooking'),
('post_workout_meal','Comida post-entreno','Proteína + carbo en 1h tras entreno.','nutrition',15,'🥪','Plato del post-entreno.',
 20, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Schoenfeld et al. (2013), doi:10.1186/1550-2783-10-5.', 'cooking'),
('fermented_food','Alimento fermentado','Yogur, kéfir, kimchi, chucrut…','nutrition',10,'🧫','Foto del fermentado.',
 null, 0, '{}', '{none}', 1, '{}', 'moderate',
 'Marco et al. (2017), doi:10.1016/j.copbio.2016.11.010.', 'none')
on conflict (slug) do update set
  title              = excluded.title,
  description        = excluded.description,
  category           = excluded.category,
  base_points        = excluded.base_points,
  icon               = excluded.icon,
  photo_hint         = excluded.photo_hint,
  duration_min       = excluded.duration_min,
  calories_burned    = excluded.calories_burned,
  equipment_required = excluded.equipment_required,
  muscle_groups      = excluded.muscle_groups,
  difficulty         = excluded.difficulty,
  contraindications  = excluded.contraindications,
  evidence_level     = excluded.evidence_level,
  references_text    = excluded.references_text,
  subcategory        = excluded.subcategory;
